# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20170331_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('login', 'login'), ('join', 'join'), ('leave', 'leave'), ('waitlist-add', 'waitlist-add'), ('waitlist-left', 'waitlist-left')], max_length=80),
        ),
    ]
