# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_waiting', models.BooleanField(default=False)),
                ('started_to_wait', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='group',
            old_name='gp',
            new_name='gfp',
        ),
        migrations.AddField(
            model_name='group_formation_process',
            name='has_been_pushed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group_formation_process',
            name='push_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='When was the group formation pushed to Brightspace?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlist',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formation.Group'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Person'),
        ),
    ]
