# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_auto_20170330_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Person')),
            ],
        ),
    ]
