# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_group_formation_process_allow_multi_enrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_formation_process',
            name='allow_unenroll',
        ),
    ]
