# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_remove_group_formation_process_allow_unenroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_formation_process',
            name='push_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When was the group formation pushed to Brightspace?'),
        ),
    ]
