# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_auto_20170331_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'create'), ('login', 'login'), ('group-join', 'group-join'), ('group-leave', 'group-leave'), ('waitlist-add', 'waitlist-add'), ('waitlist-left', 'waitlist-left')], max_length=80)),
                ('ip_address', models.GenericIPAddressField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('gfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formation.Group_Formation_Process')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formation.Group')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formation.Person')),
            ],
        ),
    ]
