# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_auto_20170405_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_formation_process',
            name='added_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
