# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0009_group_formation_process_added_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_formation_process',
            name='dt_group_selection_stops',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When does group enrolment stop?'),
            preserve_default=False,
        ),
    ]
