# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0011_auto_20170412_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, help_text='An empty name is effectively a non-existant group.', max_length=500, verbose_name='Group name'),
        ),
    ]
