# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_auto_20170412_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_formation_process',
            name='dt_group_selection_stops',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='When does group enrolment stop?'),
        ),
    ]
