# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0013_auto_20170424_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_firstname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='person_lastname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
